import type {
  Category,
  MilkOption,
  Product,
  SizeOption,
} from "./types";

export const categories: Category[] = [
  { id: "quentes", label: "Quentes", glyph: "◐" },
  { id: "gelados", label: "Gelados", glyph: "◇" },
  { id: "salgados", label: "Salgados", glyph: "▢" },
  { id: "doces", label: "Doces", glyph: "○" },
];

export const sizeOptions: SizeOption[] = [
  { id: "p", label: "P", detail: "240 ml", priceDelta: 0 },
  { id: "m", label: "M", detail: "320 ml", priceDelta: 3 },
  { id: "g", label: "G", detail: "400 ml", priceDelta: 5.5 },
];

export const milkOptions: MilkOption[] = [
  { id: "integral", label: "Leite integral", priceDelta: 0 },
  { id: "desnatado", label: "Leite desnatado", priceDelta: 0 },
  { id: "aveia", label: "Leite de aveia", priceDelta: 3 },
  { id: "amendoas", label: "Leite de amêndoas", priceDelta: 3 },
  { id: "nenhum", label: "Sem leite", priceDelta: 0 },
];

export const products: Product[] = [
  {
    id: "espresso",
    categoryId: "quentes",
    name: "Espresso",
    description: "Extração curta, corpo denso, notas de cacau.",
    basePrice: 7,
    tag: "Clássico",
    customizable: true,
  },
  {
    id: "flat-white",
    categoryId: "quentes",
    name: "Flat White",
    description: "Duplo espresso, leite vaporizado em camada fina.",
    basePrice: 12.5,
    tag: "Favorito",
    customizable: true,
  },
  {
    id: "cappuccino",
    categoryId: "quentes",
    name: "Cappuccino",
    description: "Espresso, leite vaporizado e espuma generosa.",
    basePrice: 11,
    customizable: true,
  },
  {
    id: "coado",
    categoryId: "quentes",
    name: "Coado do dia",
    description: "Método filtro, grão de origem única, safra atual.",
    basePrice: 9,
    tag: "Origem única",
    customizable: false,
  },
  {
    id: "mocha",
    categoryId: "quentes",
    name: "Mocha",
    description: "Espresso, chocolate 70% e leite vaporizado.",
    basePrice: 13,
    customizable: true,
  },
  {
    id: "cold-brew",
    categoryId: "gelados",
    name: "Cold Brew",
    description: "Infusão a frio por 16h, doçura natural, sem amargor.",
    basePrice: 12,
    tag: "16h de infusão",
    customizable: true,
  },
  {
    id: "latte-gelado",
    categoryId: "gelados",
    name: "Latte Gelado",
    description: "Espresso duplo, leite gelado, gelo em cubos.",
    basePrice: 13.5,
    customizable: true,
  },
  {
    id: "affogato",
    categoryId: "gelados",
    name: "Affogato",
    description: "Sorvete de baunilha afogado em espresso quente.",
    basePrice: 15,
    tag: "Sobremesa",
    customizable: false,
  },
  {
    id: "cha-gelado",
    categoryId: "gelados",
    name: "Chá Gelado de Hibisco",
    description: "Infusão floral, leve acidez, servido com gelo.",
    basePrice: 10,
    customizable: false,
  },
  {
    id: "pao-queijo",
    categoryId: "salgados",
    name: "Pão de Queijo",
    description: "Porção com 4 unidades, servido quente.",
    basePrice: 9,
    customizable: false,
  },
  {
    id: "croissant-presunto",
    categoryId: "salgados",
    name: "Croissant de Presunto e Queijo",
    description: "Folhado amanteigado, recheio derretido na hora.",
    basePrice: 16,
    tag: "Assado na hora",
    customizable: false,
  },
  {
    id: "sanduiche-natural",
    categoryId: "salgados",
    name: "Sanduíche Natural",
    description: "Pão integral, frango desfiado, ricota e rúcula.",
    basePrice: 18,
    customizable: false,
  },
  {
    id: "croissant",
    categoryId: "doces",
    name: "Croissant Simples",
    description: "Folhas crocantes, manteiga francesa.",
    basePrice: 10,
    customizable: false,
  },
  {
    id: "bolo-cenoura",
    categoryId: "doces",
    name: "Bolo de Cenoura com Chocolate",
    description: "Fatia generosa, cobertura cremosa.",
    basePrice: 11,
    customizable: false,
  },
  {
    id: "cookie",
    categoryId: "doces",
    name: "Cookie de Chocolate",
    description: "Casquinha crocante, centro macio.",
    basePrice: 8,
    tag: "Assado hoje",
    customizable: false,
  },
];
